name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      # It's hard to get ssh+sshd setup correct! Here's a reference which helped with this
      # https://github.com/peznauts/octahe.swift/blob/3b4f117ee2f44406ffd044224cba1803d02e0368/.github/workflows/swift-docker-pull.yml#L46-L75
      # via https://github.community/t/unable-to-ssh-to-localhost-22/18304/2
      - name: Set up passwordless SSH access for localhost
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 127.111.111.111 >> ~/.ssh/known_hosts
          ssh-keygen -N '' -f ~/.ssh/id_rsa_remoterepl_test
          cat ~/.ssh/id_rsa_remoterepl_test.pub >> ~/.ssh/authorized_keys
          echo -e "\nHost 127.111.111.111\n  IdentityFile ~/.ssh/id_rsa_remoterepl_test" >> ~/.ssh/config
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa_remoterepl_test
      - name: The gauntlet of correct ssh permissions
        run: |
          chmod 600 ~/.ssh/*
          chmod 700 ~/.ssh
          sudo chmod -c 0755 ~/
      # - name: Verify ssh config
      #   run: |
      #     sudo cat /etc/ssh/sshd_config
      #     ls -l ~/.ssh
      #     ls -ld ~
      #     cat ~/.ssh/authorized_keys
      - name: Test ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -vvv 127.111.111.111 true
      # - name: sshd logs
      #   run: |
      #     journalctl -t sshd
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - run: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(; path=pwd()));
          Pkg.instantiate();'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
